server:
  port: 8008

spring:
  application:
    name: drone-system-file
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
      config:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        file-extension: yaml
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB