server:
  port: 8009

spring:
  application:
    name: drone-system-search
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
      config:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        file-extension: yaml
  elasticsearch:
    uris: ${ES_URIS:http://127.0.0.1:9200}